spring:
  datasource:
      url: jdbc:mysql://localhost/post_list?useSSL=false
      username: root
      password:
      driverClassName: com.mysql.jdbc.Driver

  jpa:
      hibernate:
        ddl-auto: none
